include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
    unnecessary_underscores: ignore
    unnecessary_import: ignore
    prefer_initializing_formals: ignore
    strict_top_level_inference: ignore

linter:
  rules:
    avoid_print: false
